---
name: "Add new issues to Ignite GH Project"

'on':
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT }}

  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels to new issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueLabels = process.env.ISSUE_LABEL ?
              process.env.ISSUE_LABEL.split(',').map(label =>
                label.trim()) : [];

            if (issueLabels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: issueLabels
              });
              console.log(`Added labels: ${issueLabels.join(', ')}`);
            } else {
              console.log('No labels specified in ISSUE_LABEL secret');
            }
        env:
          ISSUE_LABEL: ${{ secrets.ISSUE_LABEL }}
